#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Keep the generated wizard library unchanged while accepting both the simple
# KEY=value files it writes and safely quoted values from hand-authored files.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value first last
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value=${line#*=}
  if [[ ${#value} -ge 2 ]]; then
    first=${value:0:1}
    last=${value:$((${#value} - 1)):1}
    if [[ ( "$first" == '"' && "$last" == '"' ) || ( "$first" == "'" && "$last" == "'" ) ]]; then
      value=${value:1:$((${#value} - 2))}
    fi
  fi
  printf '%s' "$value"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE="$ROOT_DIR/.env"
fi
DEPLOY_LOG=""
WORKER_URL=""

cd "$ROOT_DIR"

require_value() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$key cannot be empty. Re-run this wizard when you have it."
    exit 1
  fi
}

wait_for_json() {
  local url="$1" result attempt
  shift
  for attempt in {1..15}; do
    if result=$(curl --fail --silent --show-error "$@" "$url" 2>/dev/null); then
      printf '%s' "$result"
      return 0
    fi
    sleep 2
  done
  warn "The Worker did not receive Notion's verification request within 30 seconds. Check the webhook URL, then re-run this wizard."
  return 1
}

wait_for_json_field() {
  local field="$1" url="$2" result value attempt
  shift 2
  for attempt in {1..15}; do
    if result=$(curl --fail --silent --show-error "$@" "$url" 2>/dev/null); then
      value=$(printf '%s' "$result" | uv run python -c "import json,sys; print(json.load(sys.stdin).get('$field', ''))" 2>/dev/null || true)
      if [[ -n "$value" ]]; then
        printf '%s' "$result"
        return 0
      fi
    fi
    sleep 2
  done
  warn "The Worker did not receive Notion's verification request within 30 seconds. Check the webhook URL, then re-run this wizard."
  return 1
}

cleanup() {
  [[ -z "$DEPLOY_LOG" || ! -f "$DEPLOY_LOG" ]] || rm -f "$DEPLOY_LOG"
}
trap cleanup EXIT

banner "Notion CalDAV Sync on Cloudflare"

stage "Connect Cloudflare"
say "Choose personal for your own calendar. Hosted is the advanced multi-user OAuth service."
if ! command -v uv >/dev/null 2>&1; then
  warn "uv is not installed yet."
  open_url "https://docs.astral.sh/uv/getting-started/installation/"
  step "Install uv using the official instructions, then run this wizard again."
  exit 1
fi

if ! command -v npx >/dev/null 2>&1; then
  if command -v mise >/dev/null 2>&1; then
    say "Installing the project-pinned Node.js runtime with mise."
    mise install node@24.21.0
    PATH="$(mise where node@24.21.0)/bin:$PATH"
    export PATH
  else
    warn "Node.js is required by Cloudflare Wrangler, and mise is not installed."
    open_url "https://mise.jdx.dev/getting-started.html"
    step "Install mise, then run this wizard again; the pinned Node.js version installs automatically."
    exit 1
  fi
fi
uv sync --group dev

ask DEPLOYMENT_MODE "Setup type (personal or hosted) [personal]:"
DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-personal}
case "$DEPLOYMENT_MODE" in
  personal|hosted) ;;
  *) warn "Deployment mode must be personal or hosted."; exit 1 ;;
esac
write_env DEPLOYMENT_MODE "$DEPLOYMENT_MODE"
export DEPLOYMENT_MODE

for key in CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_STATE_NAMESPACE; do
  value=$(_existing "$key" || true)
  if [[ -n "$value" ]]; then
    printf -v "$key" '%s' "$value"
    export "$key"
  fi
done

if uv run -- pywrangler whoami >/dev/null 2>&1; then
  say "Cloudflare authentication is ready."
else
  step "Approve the Cloudflare authorization page that opens in your browser."
  uv run -- pywrangler login
  uv run -- pywrangler whoami >/dev/null
  say "Cloudflare authentication succeeded."
fi

ask WORKER_CUSTOM_DOMAIN "Custom domain [Enter uses workers.dev or keeps the saved value; type - to clear]:"
WORKER_CUSTOM_DOMAIN=$(printf "%s" "$WORKER_CUSTOM_DOMAIN" | tr '[:upper:]' '[:lower:]' | xargs)
[[ "$WORKER_CUSTOM_DOMAIN" == "-" ]] && WORKER_CUSTOM_DOMAIN=""
if [[ -n "$WORKER_CUSTOM_DOMAIN" && ! "$WORKER_CUSTOM_DOMAIN" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]]; then
  warn "Enter a hostname without https:// or a path."
  exit 1
fi
write_env WORKER_CUSTOM_DOMAIN "$WORKER_CUSTOM_DOMAIN"
export WORKER_CUSTOM_DOMAIN
export WORKER_ENDPOINT_CONFIGURED=1
if [[ -n "$WORKER_CUSTOM_DOMAIN" ]]; then
  WORKER_URL="https://$WORKER_CUSTOM_DOMAIN"
elif [[ "$DEPLOYMENT_MODE" == "hosted" ]]; then
  PUBLIC_BASE_URL=$(_existing PUBLIC_BASE_URL || true)
  if [[ ! "$PUBLIC_BASE_URL" =~ ^https://notion-caldav-sync\.[a-zA-Z0-9-]+\.workers\.dev$ || "$PUBLIC_BASE_URL" == *.example.workers.dev ]]; then
    say "Hosted OAuth needs the final callback URL before deployment."
    open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
    step "In Workers & Pages, find your account's workers.dev subdomain."
    ask WORKERS_DEV_SUBDOMAIN "Account subdomain (the part before .workers.dev):"
    WORKERS_DEV_SUBDOMAIN=$(printf "%s" "$WORKERS_DEV_SUBDOMAIN" | tr '[:upper:]' '[:lower:]' | xargs)
    if [[ ! "$WORKERS_DEV_SUBDOMAIN" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
      warn "Enter only the account subdomain, without .workers.dev."
      exit 1
    fi
    PUBLIC_BASE_URL="https://notion-caldav-sync.${WORKERS_DEV_SUBDOMAIN}.workers.dev"
  fi
  PUBLIC_BASE_URL=${PUBLIC_BASE_URL%/}
  WORKER_URL="$PUBLIC_BASE_URL"
  write_env PUBLIC_BASE_URL "$PUBLIC_BASE_URL"
  export PUBLIC_BASE_URL
else
  say "Cloudflare will assign a free notion-caldav-sync.<account-subdomain>.workers.dev URL."
fi

stage "Connect Notion"
open_url "https://www.notion.so/profile/integrations"
if [[ "$DEPLOYMENT_MODE" == "personal" ]]; then
  say "Create an internal connection with read-content access. This stable, least-privilege option also provides the Webhooks tab required later."
  step "Share every page or data source you want to sync with that connection."
  ask_secret NOTION_TOKEN "Paste the Notion token:"
  require_value NOTION_TOKEN "$NOTION_TOKEN"
  write_env NOTION_TOKEN "$NOTION_TOKEN"
  export NOTION_TOKEN
else
  say "Create a public connection. Notion does not expose connection creation through its API."
  step "Set the OAuth redirect URI to: ${WORKER_URL%/}/notion/callback"
  step "Choose Any workspace for a public service, or Selected workspaces only for a private deployment."
  step "Use Notion API version 2026-03-11 and enable read-content access."
  ask NOTION_CLIENT_ID "Notion OAuth client ID:"
  require_value NOTION_CLIENT_ID "$NOTION_CLIENT_ID"
  ask_secret NOTION_CLIENT_SECRET "Notion OAuth client secret:"
  require_value NOTION_CLIENT_SECRET "$NOTION_CLIENT_SECRET"
  write_env NOTION_CLIENT_ID "$NOTION_CLIENT_ID"
  write_env NOTION_CLIENT_SECRET "$NOTION_CLIENT_SECRET"
  export NOTION_CLIENT_ID NOTION_CLIENT_SECRET
fi

stage "Connect Apple Calendar or set up sign-in"
if [[ "$DEPLOYMENT_MODE" == "personal" ]]; then
  say "Use an app-specific password. Your normal Apple Account password will not work."
  open_url "https://account.apple.com/"
  step "Open Sign-In and Security → App-Specific Passwords and create one named notion-caldav-sync."
  ask APPLE_ID "Apple Account email:"
  require_value APPLE_ID "$APPLE_ID"
  ask_secret APPLE_APP_PASSWORD "Paste the app-specific password:"
  require_value APPLE_APP_PASSWORD "$APPLE_APP_PASSWORD"
  write_env APPLE_ID "$APPLE_ID"
  write_env APPLE_APP_PASSWORD "$APPLE_APP_PASSWORD"
  export APPLE_ID APPLE_APP_PASSWORD

  ADMIN_TOKEN=$(_existing ADMIN_TOKEN || true)
  if [[ -z "$ADMIN_TOKEN" ]]; then
    ADMIN_TOKEN=$(openssl rand -hex 32)
    write_env ADMIN_TOKEN "$ADMIN_TOKEN"
    say "Generated a private admin token."
  else
    say "Keeping the existing admin token."
  fi
  export ADMIN_TOKEN
  WEBHOOK_SETUP_TOKEN=$(_existing WEBHOOK_SETUP_TOKEN || true)
  if [[ -z "$WEBHOOK_SETUP_TOKEN" ]]; then
    WEBHOOK_SETUP_TOKEN=$(openssl rand -hex 32)
    write_env WEBHOOK_SETUP_TOKEN "$WEBHOOK_SETUP_TOKEN"
  fi
  export WEBHOOK_SETUP_TOKEN
else
  say "The hosted service uses Clerk for user and administrator identity."
  open_url "https://dashboard.clerk.com/"
  ask CLERK_PUBLISHABLE_KEY "Clerk publishable key:"
  require_value CLERK_PUBLISHABLE_KEY "$CLERK_PUBLISHABLE_KEY"
  ask CLERK_JWKS_URL "Clerk JWKS URL:"
  require_value CLERK_JWKS_URL "$CLERK_JWKS_URL"
  ask CLERK_SIGN_IN_URL "Clerk sign-in URL:"
  require_value CLERK_SIGN_IN_URL "$CLERK_SIGN_IN_URL"
  ask CLERK_AUTHORIZED_PARTIES "Allowed origins, comma-separated [${WORKER_URL}]:"
  CLERK_AUTHORIZED_PARTIES=${CLERK_AUTHORIZED_PARTIES:-$WORKER_URL}
  step "Open Clerk Dashboard → Users → your account and copy its user ID."
  ask HOSTED_ADMIN_USER_IDS "Administrator Clerk user IDs, comma-separated:"
  require_value HOSTED_ADMIN_USER_IDS "$HOSTED_ADMIN_USER_IDS"
  for key in CLERK_PUBLISHABLE_KEY CLERK_JWKS_URL CLERK_SIGN_IN_URL CLERK_AUTHORIZED_PARTIES HOSTED_ADMIN_USER_IDS; do
    write_env "$key" "${!key}"
    export "$key"
  done
  if [[ -n "$WORKER_CUSTOM_DOMAIN" ]]; then
    PUBLIC_BASE_URL="$WORKER_URL"
    write_env PUBLIC_BASE_URL "$PUBLIC_BASE_URL"
    export PUBLIC_BASE_URL
  fi
fi
chmod 600 "$ENV_FILE"

stage "Deploy"
STATUS_EMOJI_STYLE=$(_existing STATUS_EMOJI_STYLE || true)
STATUS_EMOJI_STYLE=${STATUS_EMOJI_STYLE:-emoji}
case "$STATUS_EMOJI_STYLE" in
  emoji|symbol) ;;
  *) warn "Status style must be emoji or symbol."; exit 1 ;;
esac
write_env STATUS_EMOJI_STYLE "$STATUS_EMOJI_STYLE"
chmod 600 "$ENV_FILE"
export STATUS_EMOJI_STYLE

say "Creating or reusing Cloudflare resources, uploading secrets, applying migrations, and deploying the Worker."
DEPLOY_LOG=$(mktemp)
if [[ "$DEPLOYMENT_MODE" == "hosted" ]]; then
  "$ROOT_DIR/scripts/provision-hosted-cloudflare.sh" | tee "$DEPLOY_LOG"
else
  "$ROOT_DIR/deploy.sh" | tee "$DEPLOY_LOG"
fi

DEPLOYED_WORKER_URL=$(sed -n 's/^Worker URL: \(https:\/\/.*\)$/\1/p' "$DEPLOY_LOG" | tail -n1)
if [[ -n "$DEPLOYED_WORKER_URL" ]]; then
  WORKER_URL="${DEPLOYED_WORKER_URL%/}"
fi
require_value worker_url "$WORKER_URL"
if [[ "$DEPLOYMENT_MODE" == "hosted" && "${PUBLIC_BASE_URL%/}" != "$WORKER_URL" ]]; then
  warn "Cloudflare deployed to $WORKER_URL, but PUBLIC_BASE_URL is ${PUBLIC_BASE_URL%/}. Correct the workers.dev subdomain or custom domain and re-run the wizard."
  exit 1
fi
wait_for_json "${WORKER_URL%/}/health" >/dev/null
say "Deployment health check passed."

stage "Verify sync"
say "Notion webhook setup is required for real-time sync. Scheduled reconciliation remains the fallback for missed or delayed deliveries."
open_url "https://www.notion.so/profile/integrations"
if [[ "$DEPLOYMENT_MODE" == "hosted" ]]; then
  HOSTED_WEBHOOK_SETUP_TOKEN=$(_existing HOSTED_WEBHOOK_SETUP_TOKEN || true)
  if [[ -z "$HOSTED_WEBHOOK_SETUP_TOKEN" ]]; then
    say "The existing remote webhook setup credential was preserved, but Cloudflare secrets cannot be read back."
    step "In the Notion Public Connection, confirm that the existing webhook subscription is Active."
    step "If it is missing, set a new HOSTED_WEBHOOK_SETUP_TOKEN in .env and re-run the wizard to rotate it."
    pause "Press Enter after confirming the existing subscription is active."
  else
    WEBHOOK_URL="${WORKER_URL%/}/webhook/notion/hosted?setup=${HOSTED_WEBHOOK_SETUP_TOKEN}"
    VERIFY_JSON=$(curl --fail --silent --show-error "${WORKER_URL%/}/api/webhook/setup?setup=${HOSTED_WEBHOOK_SETUP_TOKEN}" 2>/dev/null || true)
    VERIFY_TOKEN=$(printf '%s' "$VERIFY_JSON" | uv run python -c 'import json,sys; print(json.load(sys.stdin).get("verification_token", ""))')
    if [[ -n "$VERIFY_TOKEN" ]]; then
      say "Webhook verification data already exists. If Notion still shows Pending, paste this token: $VERIFY_TOKEN"
      pause "Press Enter after the subscription shows Active."
    else
      step "Create a webhook subscription with this URL: $WEBHOOK_URL"
      step "Subscribe to Page, Database, and Data source events."
      pause "Press Enter after Notion sends the verification request."
      VERIFY_JSON=$(wait_for_json_field verification_token "${WORKER_URL%/}/api/webhook/setup?setup=${HOSTED_WEBHOOK_SETUP_TOKEN}")
      VERIFY_TOKEN=$(printf '%s' "$VERIFY_JSON" | uv run python -c 'import json,sys; print(json.load(sys.stdin).get("verification_token", ""))')
      require_value verification_token "$VERIFY_TOKEN"
      say "Paste this verification token into Notion: $VERIFY_TOKEN"
      pause "Press Enter after Notion reports the subscription as active."
    fi
  fi
else
  VERIFY_JSON=$(curl --fail --silent --show-error \
    --header "X-Admin-Token: $ADMIN_TOKEN" \
    "${WORKER_URL%/}/admin/settings" 2>/dev/null || true)
  VERIFY_TOKEN=$(printf '%s' "$VERIFY_JSON" | uv run python -c 'import json,sys; print(json.load(sys.stdin).get("webhook_verification_token", ""))' 2>/dev/null || true)
  if [[ -n "$VERIFY_TOKEN" ]]; then
    say "Webhook verification data already exists. If Notion still shows Pending, paste this token: $VERIFY_TOKEN"
    pause "Press Enter after the subscription shows Active."
  else
    step "Create a webhook subscription with this private setup URL: ${WORKER_URL%/}/webhook/notion?setup=${WEBHOOK_SETUP_TOKEN}"
    step "Do not post the setup URL in issues, logs, or screenshots."
    step "Subscribe to Page, Database, and Data source events."
    pause "Press Enter after Notion sends the verification request."
    VERIFY_JSON=$(wait_for_json_field webhook_verification_token "${WORKER_URL%/}/admin/settings" \
      --header "X-Admin-Token: $ADMIN_TOKEN")
    VERIFY_TOKEN=$(printf '%s' "$VERIFY_JSON" | uv run python -c 'import json,sys; print(json.load(sys.stdin).get("webhook_verification_token", ""))')
    require_value verification_token "$VERIFY_TOKEN"
    say "Paste this verification token into Notion: $VERIFY_TOKEN"
    pause "Press Enter after Notion reports the subscription as active."
  fi
fi
if [[ "$DEPLOYMENT_MODE" == "personal" ]]; then
  LAST_FULL_SYNC=$(printf '%s' "$VERIFY_JSON" | uv run python -c 'import json,sys; print(json.load(sys.stdin).get("last_full_sync", ""))' 2>/dev/null || true)
  if [[ -z "$LAST_FULL_SYNC" ]]; then
    say "Running the first full sync now."
    curl --fail --silent --show-error \
      --request POST \
      --header "X-Admin-Token: $ADMIN_TOKEN" \
      "${WORKER_URL%/}/admin/full-sync" >/dev/null
    say "Initial full sync completed."
  else
    say "Existing sync history found; no duplicate full sync was started."
  fi
fi
# ──────────────────────────────────────────────────────────────────────────

finish
say "Worker: $WORKER_URL"
if [[ "$DEPLOYMENT_MODE" == "hosted" ]]; then
  say "OAuth callback: ${WORKER_URL%/}/notion/callback"
  say "Administrator console: ${WORKER_URL%/}/admin"
else
  say "Webhook: ${WORKER_URL%/}/webhook/notion"
fi
